weatherDict = {
    0: 'Clear sky',
    1: 'The weather is mainly clear at the moment',
    2: 'It is partly clouded at the moment',
    3: 'There is a overcast at the moment',
    45: 'There is fog at the moment',
    48: 'There is depositing rime fog at the moment',
    51: 'There is light drizzle at the moment',
    53: 'There is moderate drizzle at the moment',
    55: 'There is heavy drizzle at the moment',
    56: 'There is slight freezing drizzle at the moment, take care!',
    57: 'There is dense freezing drizzle at the moment, take care!',
    61: 'It is slightly raining at the moment',
    63: 'It is raining at the moment',
    65: 'There is heavy rain at the moment',
    66: 'There is light freezing rain at the moment',
    67: 'There is heavy freezing rain at the moment, take care!',
    71: 'It is slightly snowing at the moment',
    73: 'It is snowing at the moment',
    75: 'There is heavy snow at the moment',
    77: 'There is snowgrain at the moment',
    80: 'There is more rain than normal',
    81: 'It is raining very hard',
    82: 'You should probably go inside',
    85: 'It is snowing more than normal',
    86: 'There is heavy snow at the moment',
    95: 'There is a thunderstorm at the moment',
    96: 'There is a thunderstorm with rain at the moment',
    99: 'There is a heavy thunderstorm with hail at the moment'
}